@id=e3e3713a-4230-427e-bf90-514cca9467f1

PUT  https://localhost:7168/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "V",
    "description": "",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}